name: Bug Report
description: Suggest an idea for this project
title: [FEAT]: (Enter short, one sentence summary of feature here)"
labels: ["enhancement"]
assignees:
  - Codezilla-Club
  body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell me, what did you expect to happen?
      placeholder: Tell me what you see!
      value: "Well, I was trying to ... but then ..."
    validations:
      required: true
  - type: textarea
    id: proposed-method
    attributes:
      label: Proposed Method
      description: Proposed Method of the feature you want to add.
    validations:
      required: true     
      - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: (Screenshots can be uploaded by simply dragging an image file into this box)
